name: OSF Guest Invite Issue
description: Use this form to invite a guest to Open Source Friday or have guests submit their information.
title: Open Source Friday - [PROJECT NAME] - [MM-DD-YYYY]
labels: ["open-source-friday", "open-source", "twitch", "pending"]
assignees: ["LadyKerr", "AndreaGriffiths11"]

body:
  - type: markdown
    attributes:
      value: |
        ## Open Source Friday Guest Invite Form
        #### :sparkles: Please fill out the following information to be invited to Open Source Friday. The stream occurs weekly at 1pm EST on the [GitHub Twitch Channel](https://www.twitch.tv/github). :sparkles:

  - type: input
    id: name
    attributes:
      label: Name
      description: Your name
      placeholder: "Kedasha Kerr"

  - type: input
    id: project_name_1
    attributes:
      label: Project Name
      description: The name of the project you'd like to showcase and chat about
      placeholder: "Awesome Project"

  - type: input
    id: project_repo_1
    attributes:
      label: Project Repo
      description: The github repository of your project
      placeholder: "github.com/repo-url"

  - type: checkboxes
    id: stream_date
    attributes:
      label: Stream Date
      description: Did you schedule a date for your stream?
      options:
        - label: "Yes"
          required: true
        - label: "Not yet"
          required: true

  - type: input
    id: dates_1
    attributes:
      label: Dates
      description: what date did you schedule for Open Source Friday stream?
      placeholder: MM-DD-YYYY

  - type: input
    id: social_twitter
    attributes:
      label: Twitter URL
      description: Your Twitter profile
      placeholder: "@itsthatladydev"

  - type: input
    id: social_linkedin
    attributes:
      label: LinkedIn URL
      description: Your LinkedIn profile
      placeholder: "linkedin.com/in/your-profile"

  - type: textarea
    id: more_info
    attributes:
      label: Additional Information
      description: Please share any additional details you'd like us to know about your project
      placeholder: "I'd like to talk about..."
