name: Send Instructions to Guest

on:
  issues:
    types: [labeled]

jobs:
  send-instructions:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'scheduled'
    steps:
      - name: Comment on issue
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueBody = context.payload.issue.body;
            const githubHandle = issueBody.match(/@(\w+)/)[1];
            const issueComment = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Hey @${githubHandle}✨,\n\nYou're officially scheduled for **Open Source Friday**! 🚀🎥. Here are some guidelines on preparing for the live stream:\n\n [Preparation Instructions](https://gist.github.com/LadyKerr/9b7d6dccde55b3f30398612d1290b7dc)\n\nLet us know if you have any questions!,\nKedasha & Andrea 👯`
            };                      github.rest.issues.createComment(issueComment);
